### ISSUE TITLE
Cannot update to 3.0.5

### ISSUE THREAD

**Issue by HudsonMC16** [hassio-addons/addon-influxdb#33]
When trying to update from 3.0.4 to 3.0.5 I get the following error in the hassio logs:

```
19-05-08 23:40:11 INFO (SyncWorker_2) [hassio.docker.interface] Update image hassioaddons/influxdb-amd64:v3.0.4 to hassioaddons/influxdb-amd64:3.0.5
19-05-08 23:40:11 INFO (SyncWorker_2) [hassio.docker.interface] Pull image hassioaddons/influxdb-amd64 tag 3.0.5.
19-05-08 23:40:30 ERROR (SyncWorker_2) [hassio.docker.interface] Can't install hassioaddons/influxdb-amd64:3.0.5 -> 404 Client Error: Not Found ("no such image: hassioaddons/influxdb-amd64:3.0.5: No such image: hassioaddons/influxdb-amd64:3.0.5").
```

The version tags look like they're formatted a bit differently...is the name of the to-be-installed image correct?

**Comment by sinclairpaul** [comment]
Looks ok to me https://hub.docker.com/r/hassioaddons/influxdb-amd64/tags  
Name resolution, space issue?

![image](https://user-images.githubusercontent.com/24625998/57416397-30f3da80-71ce-11e9-997d-006836ec141e.png)

**Comment by sinclairpaul** [comment]
Closing, as assume it is resolved.

**Comment by HudsonMC16** [comment]
Yeah, I'm sorry I went silent on this. I'm still not able to install, but if it's just isolated to me, I'll get it figured out. Sorry for clogging up the issue reports. Thanks!

**Comment by sinclairpaul** [comment]
No worries, pretty sure its likely a disk space issue though.
